{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "portfolio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "portfolio.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
    {{- if .Values.appMetrics.enabled }}
    - port: app-metrics
      path: /metrics
      interval: 30s
    {{- end }}
{{- end }}
